package com.qdenbs.db.table.entity;

import java.util.Date;

public class FileEntity extends FileKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.file.file_path
     *
     * @mbg.generated
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.file.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.file.file_size
     *
     * @mbg.generated
     */
    private String fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.file.file_title
     *
     * @mbg.generated
     */
    private String fileTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.file.regist_dt
     *
     * @mbg.generated
     */
    private Date registDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.file.update_dt
     *
     * @mbg.generated
     */
    private Date updateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.file.file_path
     *
     * @return the value of public.file.file_path
     *
     * @mbg.generated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.file.file_path
     *
     * @param filePath the value for public.file.file_path
     *
     * @mbg.generated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.file.file_name
     *
     * @return the value of public.file.file_name
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.file.file_name
     *
     * @param fileName the value for public.file.file_name
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.file.file_size
     *
     * @return the value of public.file.file_size
     *
     * @mbg.generated
     */
    public String getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.file.file_size
     *
     * @param fileSize the value for public.file.file_size
     *
     * @mbg.generated
     */
    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.file.file_title
     *
     * @return the value of public.file.file_title
     *
     * @mbg.generated
     */
    public String getFileTitle() {
        return fileTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.file.file_title
     *
     * @param fileTitle the value for public.file.file_title
     *
     * @mbg.generated
     */
    public void setFileTitle(String fileTitle) {
        this.fileTitle = fileTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.file.regist_dt
     *
     * @return the value of public.file.regist_dt
     *
     * @mbg.generated
     */
    public Date getRegistDt() {
        return registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.file.regist_dt
     *
     * @param registDt the value for public.file.regist_dt
     *
     * @mbg.generated
     */
    public void setRegistDt(Date registDt) {
        this.registDt = registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.file.update_dt
     *
     * @return the value of public.file.update_dt
     *
     * @mbg.generated
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.file.update_dt
     *
     * @param updateDt the value for public.file.update_dt
     *
     * @mbg.generated
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }
}