package com.qdenbs.db.table.entity;

import java.util.Date;

public class SyainEntity extends SyainKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.syain.pass
     *
     * @mbg.generated
     */
    private String pass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.syain.shimei
     *
     * @mbg.generated
     */
    private String shimei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.syain.regist_dt
     *
     * @mbg.generated
     */
    private Date registDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.syain.update_dt
     *
     * @mbg.generated
     */
    private Date updateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.syain.pass
     *
     * @return the value of public.syain.pass
     *
     * @mbg.generated
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.syain.pass
     *
     * @param pass the value for public.syain.pass
     *
     * @mbg.generated
     */
    public void setPass(String pass) {
        this.pass = pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.syain.shimei
     *
     * @return the value of public.syain.shimei
     *
     * @mbg.generated
     */
    public String getShimei() {
        return shimei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.syain.shimei
     *
     * @param shimei the value for public.syain.shimei
     *
     * @mbg.generated
     */
    public void setShimei(String shimei) {
        this.shimei = shimei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.syain.regist_dt
     *
     * @return the value of public.syain.regist_dt
     *
     * @mbg.generated
     */
    public Date getRegistDt() {
        return registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.syain.regist_dt
     *
     * @param registDt the value for public.syain.regist_dt
     *
     * @mbg.generated
     */
    public void setRegistDt(Date registDt) {
        this.registDt = registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.syain.update_dt
     *
     * @return the value of public.syain.update_dt
     *
     * @mbg.generated
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.syain.update_dt
     *
     * @param updateDt the value for public.syain.update_dt
     *
     * @mbg.generated
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }
}