package com.qdenbs.db.table.entity;

public class SyainKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.syain.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.syain.id
     *
     * @return the value of public.syain.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.syain.id
     *
     * @param id the value for public.syain.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }
}