package com.qdenbs.db.table.entity;

import java.util.Date;

public class TicketEntity extends TicketKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ticket.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ticket.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ticket.text
     *
     * @mbg.generated
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ticket.tanto
     *
     * @mbg.generated
     */
    private String tanto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ticket.kosu
     *
     * @mbg.generated
     */
    private String kosu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ticket.regist_dt
     *
     * @mbg.generated
     */
    private Date registDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ticket.update_dt
     *
     * @mbg.generated
     */
    private Date updateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ticket.status
     *
     * @return the value of public.ticket.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ticket.status
     *
     * @param status the value for public.ticket.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ticket.title
     *
     * @return the value of public.ticket.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ticket.title
     *
     * @param title the value for public.ticket.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ticket.text
     *
     * @return the value of public.ticket.text
     *
     * @mbg.generated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ticket.text
     *
     * @param text the value for public.ticket.text
     *
     * @mbg.generated
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ticket.tanto
     *
     * @return the value of public.ticket.tanto
     *
     * @mbg.generated
     */
    public String getTanto() {
        return tanto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ticket.tanto
     *
     * @param tanto the value for public.ticket.tanto
     *
     * @mbg.generated
     */
    public void setTanto(String tanto) {
        this.tanto = tanto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ticket.kosu
     *
     * @return the value of public.ticket.kosu
     *
     * @mbg.generated
     */
    public String getKosu() {
        return kosu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ticket.kosu
     *
     * @param kosu the value for public.ticket.kosu
     *
     * @mbg.generated
     */
    public void setKosu(String kosu) {
        this.kosu = kosu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ticket.regist_dt
     *
     * @return the value of public.ticket.regist_dt
     *
     * @mbg.generated
     */
    public Date getRegistDt() {
        return registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ticket.regist_dt
     *
     * @param registDt the value for public.ticket.regist_dt
     *
     * @mbg.generated
     */
    public void setRegistDt(Date registDt) {
        this.registDt = registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ticket.update_dt
     *
     * @return the value of public.ticket.update_dt
     *
     * @mbg.generated
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ticket.update_dt
     *
     * @param updateDt the value for public.ticket.update_dt
     *
     * @mbg.generated
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }
}