package com.qdenbs.db.table.mapper;

import com.qdenbs.db.table.entity.FileEntity;
import com.qdenbs.db.table.entity.FileExample;
import com.qdenbs.db.table.entity.FileKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.file
     *
     * @mbg.generated
     */
    long countByExample(FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.file
     *
     * @mbg.generated
     */
    int deleteByExample(FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(FileKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.file
     *
     * @mbg.generated
     */
    int insert(FileEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.file
     *
     * @mbg.generated
     */
    int insertSelective(FileEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.file
     *
     * @mbg.generated
     */
    List<FileEntity> selectByExample(FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.file
     *
     * @mbg.generated
     */
    FileEntity selectByPrimaryKey(FileKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.file
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FileEntity record, @Param("example") FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.file
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FileEntity record, @Param("example") FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FileEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FileEntity record);
}