package com.qdenbs.db.table.mapper;

import com.qdenbs.db.table.entity.SyainEntity;
import com.qdenbs.db.table.entity.SyainExample;
import com.qdenbs.db.table.entity.SyainKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SyainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.syain
     *
     * @mbg.generated
     */
    long countByExample(SyainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.syain
     *
     * @mbg.generated
     */
    int deleteByExample(SyainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.syain
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(SyainKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.syain
     *
     * @mbg.generated
     */
    int insert(SyainEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.syain
     *
     * @mbg.generated
     */
    int insertSelective(SyainEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.syain
     *
     * @mbg.generated
     */
    List<SyainEntity> selectByExample(SyainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.syain
     *
     * @mbg.generated
     */
    SyainEntity selectByPrimaryKey(SyainKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.syain
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SyainEntity record, @Param("example") SyainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.syain
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SyainEntity record, @Param("example") SyainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.syain
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SyainEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.syain
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SyainEntity record);
}